/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zadatak3;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author manojlovic
 */
public class Zadatak3 extends javax.swing.JFrame {

    /**
     * Creates new form Zadatak3
     */
    private Timer progressTajmer = null;
    private int count=0;
    private CenaAutomobila vest;
    public int brojac=0;
    public Zadatak3() {
        initComponents();
        System.out.println("Program ispisuje listu automobila u fajl Ispis.txt");
        Thread nit = new Thread(() -> {
            try{
                 Document doc = Jsoup.connect("http://www.polovniautomobili.com").get();
                 Elements elems = doc.select(".uk-overlay");
                 
            for (Element e : elems) {
                vest = new CenaAutomobila();
                vest.setCena(e.text());
                brojac++;
                System.out.println("Rb. " + brojac + vest.toString());
            }
            }catch(IOException e){
                System.out.println(e);
            }
        });
        
        Thread nit1 = new Thread(() -> {
            try{
                PrintStream ispis = new PrintStream(new File("Ispis.txt"));
                System.setOut(ispis);
                ispis.println("Cene:");
                ispis.println(vest.toString());
                              
            }catch(FileNotFoundException ex){
                ex.printStackTrace();
            }
        });     
//------------------------------------------------------------------------------        
        progressTajmer = new Timer(100, new ActionListener(){
            
            @Override
            public void actionPerformed(ActionEvent e) {
                
                count++;
                jProgressBar1.setValue(count);
                if(jProgressBar1.getValue() < brojac){
                    jProgressBar1.setValue(jProgressBar1.getValue() + 1);                        
                }
                if(jProgressBar1.getValue() == brojac){
                    System.exit(0);
                }
            }           
        });
//------------------------------------------------------------------------------
        nit.start();
  /*      try {
            nit.join();
        } catch (InterruptedException ex) {
            Logger.getLogger(Zadatak3.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        nit1.start();
        progressTajmer.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zadatak3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zadatak3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zadatak3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zadatak3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zadatak3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
